#ifndef COCKTAILENGINE_CORE_EXPORT_HPP
#define COCKTAILENGINE_CORE_EXPORT_HPP

#include <CocktailEngine/Core/Cocktail.hpp>

#ifdef COCKTAILENGINE_CORE_BUILD
	#define COCKTAILENGINE_CORE_API CK_EXPORT_API
#else
	#define COCKTAILENGINE_CORE_API CK_IMPORT_API
#endif

#endif // COCKTAILENGINE_CORE_EXPORT_HPP
