#ifndef COCKTAIL_GRAPHIC_EXPORT_HPP
#define COCKTAIL_GRAPHIC_EXPORT_HPP

#include <CocktailEngine/Core/Cocktail.hpp>

#ifdef COCKTAILENGINE_GRAPHIC_BUILD
	#define COCKTAILENGINE_GRAPHIC_API CK_EXPORT_API
#else
	#define COCKTAILENGINE_GRAPHIC_API CK_IMPORT_API
#endif

#endif // COCKTAIL_GRAPHIC_EXPORT_HPP
