#ifndef COCKTAIL_RENDERER_EXPORT_HPP
#define COCKTAIL_RENDERER_EXPORT_HPP

#include <Cocktail/Core/Cocktail.hpp>

#ifdef COCKTAIL_RENDERER_BUILD
	#define COCKTAIL_RENDERER_API COCKTAIL_EXPORT_API
#else
	#define COCKTAIL_RENDERER_API COCKTAIL_IMPORT_API
#endif

#endif // COCKTAIL_RENDERER_EXPORT_HPP
