#ifndef COCKTAILENGINE_VULKAN_EXPORT_HPP
#define COCKTAILENGINE_VULKAN_EXPORT_HPP

#include <CocktailEngine/Core/Cocktail.hpp>

#ifdef COCKTAILENGINE_VULKAN_BUILD
	#define COCKTAILENGINE_VULKAN_API CK_EXPORT_API
#else
	#define COCKTAILENGINE_VULKAN_API CK_IMPORT_API
#endif

#endif // COCKTAILENGINE_VULKAN_EXPORT_HPP
