#ifndef COCKTAIL_VULKAN_EXPORT_HPP
#define COCKTAIL_VULKAN_EXPORT_HPP

#include <Cocktail/Core/Cocktail.hpp>

#ifdef COCKTAIL_VULKAN_BUILD
	#define COCKTAIL_VULKAN_API COCKTAIL_EXPORT_API
#else
	#define COCKTAIL_VULKAN_API COCKTAIL_IMPORT_API
#endif

#endif // COCKTAIL_VULKAN_EXPORT_HPP
