#ifndef IMGUI_IMGUIINTEGRATION_EXPORT_HPP
#define IMGUI_IMGUIINTEGRATION_EXPORT_HPP

#include <CocktailEngine/Core/Cocktail.hpp>

#ifdef IMGUI_IMGUIINTEGRATION_BUILD
	#define IMGUI_IMGUIINTEGRATION_API CK_EXPORT_API
#else
	#define IMGUI_IMGUIINTEGRATION_API CK_IMPORT_API
#endif

#endif // IMGUI_IMGUIINTEGRATION_EXPORT_HPP
