#ifndef COCKTAIL_VULKAN_DESCRIPTORSET_ALLOCATOR_DESCRIPTORSETALLOCATORCREATEINFO_HPP
#define COCKTAIL_VULKAN_DESCRIPTORSET_ALLOCATOR_DESCRIPTORSETALLOCATORCREATEINFO_HPP

namespace Ck::Vulkan
{
	/**
	 * \brief 
	 */
	struct DescriptorSetAllocatorCreateInfo
	{
		/**
		 * \brief 
		 */
		const char* Name = nullptr;
	};
}

#endif // COCKTAIL_VULKAN_DESCRIPTORSET_ALLOCATOR_DESCRIPTORSETALLOCATORCREATEINFO_HPP
