#ifndef COCKTAILENGINE_RENDERER_EXPORT_HPP
#define COCKTAILENGINE_RENDERER_EXPORT_HPP

#include <CocktailEngine/Core/Cocktail.hpp>

#ifdef COCKTAILENGINE_RENDERER_BUILD
	#define COCKTAILENGINE_RENDERER_API CK_EXPORT_API
#else
	#define COCKTAILENGINE_RENDERER_API CK_IMPORT_API
#endif

#endif // COCKTAILENGINE_RENDERER_EXPORT_HPP
