#ifndef COCKTAIL_GRAPHIC_RENDERING_QUEUE_LINERECORDINFO_HPP
#define COCKTAIL_GRAPHIC_RENDERING_QUEUE_LINERECORDINFO_HPP

#include <Cocktail/Core/Color.hpp>
#include <Cocktail/Core/Math/Matrix/Matrix4.hpp>

#include <Cocktail/Renderer/Buffer/Buffer.hpp>

namespace Ck
{
    /**
     * \brief Describes a line rendering record submitted to the render queue
     *
     * LineRecordInfo stores all data required to issue a line draw call.
     * It is typically generated by a LineShape and consumed by the renderer
     * during the rendering phase.
     */
    struct LineRecordInfo
    {
        /**
         * \brief World transformation matrix of the line geometry
         *
         * Transforms the line vertices from local space to world space.
         */
        Matrix4<float> WorldMatrix;

        /**
         * \brief Pointer to the vertex buffer containing the line vertices
         *
         * The buffer must remain valid for the duration of the rendering pass.
         */
        Renderer::Buffer* VertexBuffer = nullptr;

        /**
         * \brief Number of points defining the line geometry
         *
         * Interpretation depends on whether the line is rendered as a strip
         * or as independent segments.
         */
        unsigned int PointCount = 0;

        /**
         * \brief Global color multiplier applied to the line
         *
         * If \ref HasVertexColor is false, this color is used directly.
         * If \ref HasVertexColor is true, the final color is computed as: finalColor = vertexColor * Color
         */
        LinearColor Color = LinearColor::White;

        /**
         * \brief Thickness of the rendered line
         *
         * The interpretation of this value depends on the rendering backend.
         */
        float Thickness = 1.f;

        /**
         * \brief Indicates whether the line is rendered as a strip
         *
         * - If true, the geometry is rendered as a line strip.
         * - If false, the geometry is rendered as independent line segments.
         */
        bool IsStrip = false;

        /**
         * \brief Indicates whether the vertex buffer contains per-vertex colors
         *
         * When true, per-vertex colors are multiplied by \ref Color to produce
         * the final rendered color.
         */
        bool HasVertexColor = false;
    };
}

#endif // COCKTAIL_GRAPHIC_RENDERING_QUEUE_LINERECORDINFO_HPP
