#ifndef COCKTAIL_GRAPHIC_RENDERING_QUEUE_STATICMESHRECORDINFO_HPP
#define COCKTAIL_GRAPHIC_RENDERING_QUEUE_STATICMESHRECORDINFO_HPP

#include <Cocktail/Core/Math/Matrix/Matrix4.hpp>
#include <Cocktail/Core/Utility/EnumMap.hpp>

#include <Cocktail/Renderer/Buffer/Buffer.hpp>
#include <Cocktail/Renderer/Renderer.hpp>
#include <Cocktail/Renderer/Texture/TextureView.hpp>

#include <Cocktail/Graphic/Geometry/Index/IndexArray.hpp>
#include <Cocktail/Graphic/Geometry/Vertex/VertexLayout.hpp>
#include <Cocktail/Graphic/Material/Material.hpp>

namespace Ck
{
    /**
     * \brief Describes a static mesh draw record submitted to the render queue
     *
     * StaticMeshRecordInfo contains all the state and resources required to issue
     * a single mesh draw call. It is typically generated by a StaticMeshShape and
     * later consumed by the renderer during command recording.
     */
    struct StaticMeshRecordInfo
    {
        /**
         * \brief Describes a vertex buffer binding
         *
         * Each entry defines a buffer, its offset, and the associated vertex layout
         * used to interpret the vertex data.
         */
        struct VertexBuffer
        {
            /**
             * \brief The GPU buffer bound as a vertex buffer
             *
             * Must remain valid for the duration of the rendering pass.
             */
            const Renderer::Buffer* Buffer = nullptr;

            /**
             * \brief Byte offset within the vertex buffer
             */
            std::size_t Offset = 0;

            /**
             * \brief Vertex layout describing the structure of the vertex data
             */
            const VertexLayout* VertexLayout = nullptr;
        };

        /**
         * \brief The number of vertices or indices to draw
         *
         * Interpreted as an index count when an index buffer is bound,
         * otherwise as a vertex count.
         */
        unsigned int Count = 0;

        /**
         * \brief First vertex index used when drawing non-indexed geometry
         */
        unsigned int FirstVertex = 0;

        /**
         * \brief First index used when drawing indexed geometry
         */
        unsigned int FirstIndex = 0;

        /**
         * \brief Number of active vertex buffer bindings
         */
        unsigned int VertexBufferCount = 0;

        /**
         * \brief Array of vertex buffer bindings
         *
         * Only the first \ref VertexBufferCount entries are valid.
         */
        VertexBuffer VertexBuffers[Renderer::MaxVertexInputBindingCount];

        /**
         * \brief The buffer bound as index buffer
         *
         * If null, the draw call is treated as non-indexed.
         */
        const Renderer::Buffer* IndexBuffer = nullptr;

        /**
         * \brief The type of indices stored in the index buffer
         */
        Renderer::IndexType IndexType = Renderer::IndexType::Integer;

        /**
         * \brief Byte offset within the index buffer
         */
        std::size_t IndexBufferOffset = 0;

        /**
         * \brief Primitive topology used for rendering
         */
        Renderer::PrimitiveTopology PrimitiveTopology = Renderer::PrimitiveTopology::Triangle;

        /**
         * \brief Indicates whether back-face culling is disabled
         *
         * When true, both front and back faces are rendered.
         */
        bool DoubleSided = false;

        /**
         * \brief Model matrix transforming the mesh from local to world space.
         */
        Matrix4<float> Model;

        /**
         * \brief Base color factor of the material
         *
         * Typically multiplies the base color texture if present.
         */
        LinearColor MaterialBaseColor;

        /**
         * \brief Emissive color factor of the material
         */
        LinearColor MaterialEmissiveColor;

        /**
         * \brief Surface roughness factor of the material
         */
        float MaterialRoughness;

        /**
         * \brief Surface metallic factor of the material
         */
        float MaterialMetallic;

        /**
         * \brief Material textures indexed by texture type
         *
         * Each texture view must remain valid during rendering.
         */
        EnumMap<Material::TextureType, std::shared_ptr<Renderer::TextureView>> MaterialTextures;

        /**
         * \brief Alpha blending mode of the material
         *
         * Determines how transparency is handled during rendering.
         */
        Material::AlphaMode AlphaMode = Material::AlphaMode::Opaque;

        /**
         * \brief Alpha cutoff threshold used for masked materials
         *
         * Fragments with alpha strictly below this value are discarded
         * when \ref AlphaMode is set to Mask.
         */
        float AlphaCutoff = 0.f;
    };
}

#endif // COCKTAIL_GRAPHIC_RENDERING_QUEUE_STATICMESHRECORDINFO_HPP
