#ifndef COCKTAILENGINE_CORE_SYSTEM_JOYSTICK_JOYSTICKAXIS_HPP
#define COCKTAILENGINE_CORE_SYSTEM_JOYSTICK_JOYSTICKAXIS_HPP

namespace Ck
{
	enum class JoystickAxis
	{
		X,
		Y,
		Z,
		R,
		U,
		V,
	};
}

#endif // COCKTAILENGINE_CORE_SYSTEM_JOYSTICK_JOYSTICKAXIS_HPP
