#ifndef COCKTAIL_D3D12_EXPORT_HPP
#define COCKTAIL_D3D12_EXPORT_HPP

#include <Cocktail/Core/Cocktail.hpp>

#ifdef COCKTAIL_D3D12_BUILD
	#define COCKTAIL_D3D12_API COCKTAIL_EXPORT_API
#else
	#define COCKTAIL_D3D12_API COCKTAIL_IMPORT_API
#endif

#endif // COCKTAIL_D3D12_EXPORT_HPP
