#ifndef COCKTAIL_GRAPHIC_EXPORT_HPP
#define COCKTAIL_GRAPHIC_EXPORT_HPP

#include <Cocktail/Core/Cocktail.hpp>

#ifdef COCKTAIL_GRAPHIC_BUILD
	#define COCKTAIL_GRAPHIC_API COCKTAIL_EXPORT_API
#else
	#define COCKTAIL_GRAPHIC_API COCKTAIL_IMPORT_API
#endif

#endif // COCKTAIL_GRAPHIC_EXPORT_HPP
